main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from main.forms import LoginForm

urlpatterns = [
	url(r'', include('social.apps.django_app.urls', namespace='social')),
	url(r'', include('django.contrib.auth.urls', namespace='auth')),
	url(r'^signup$', views.signup, name='signup'),
	url(r'^signup_ok$', TemplateView.as_view(
        template_name='registration/signup_ok.html'
    ), name='signup_ok'),
	url(r'^login', auth_views.login, {
        'authentication_form': LoginForm
    	}, name='login_url'),
	url(r'^logout', auth_views.logout, {
        'next_page': '/login',
    	}, name='logout_url'),
	url(r'^about/$', TemplateView.as_view(
        template_name='about.html'
    ), name='about'),
    url(r'^summernote', include('django_summernote.urls')),
    url(r'^$', views.home, name='home'),
    url(r'^join', views.join, name='join'),
   
    #url(r'^question/(?P<question_id>[0-9]+)/$', 'question',
    #	name='view_question'),
    # url(r'^question/(?P<question_id>[0-9]/\
    #     comment/(?P<comment_id>[0-9]+)/(?P<status>up|down)/$', 'popularity',
    #     name='comment_popularity'),
    #url(
    #    r'^question/comment/(?P<comment_id>[0-9]+)/(?P<status>up|down)/$',
    #    'popularity', name='comment_popularity'),
    #url(r'^post/$', 'post', name='post'),
]

main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class ClubList(models.Model):
	ClubName = models.CharField(max_length = 50, blank = "True")
	ClubDescription = models.TextField(max_length = 500, blank = "True")
	ClubManager1 = models.TextField(blank = "True")
	ClubManager2 = models.TextField(blank = "True")
	ClubMemberSum = models.IntegerField(blank = "True")

    #class Meta:
    #    ordering = ['-ClubMemberSum']

    #def __unicode__(self):
    #    return u"{0}".format(self.ClubName)

class Question(models.Model):
    """question
    when a user posts questions
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=300)
    content = models.TextField()
    tags = models.ManyToManyField('Tag')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated_at']

    def __unicode__(self):
        return u"{0}".format(self.title)


class Comment(models.Model):
    """comments
    comments in one question
    """
    question = models.ForeignKey(Question)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    popularity = models.PositiveIntegerField(default=0)
    content = models.TextField(max_length=600)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-popularity', '-created_at']
        get_latest_by = 'created_at'

    def __unicode__(self):
        return u'Q: {0} - Comment: {1}'.format(self.question.id, self.id)


class Tag(models.Model):
    """Tag
    Tag in question
    """
    name = models.CharField(max_length=80, blank=True)

    def __unicode__(self):
        return u"{0}".format(self.name)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from main.models import Question, Comment
from django_summernote.widgets import SummernoteWidget


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(SignupForm, self).__init__(*args, **kwargs)

    username = forms.RegexField(
        max_length=30,
        regex=r'^[\w.@+-]+$',
        error_messages={
            'invalid': "This value may contain only letters, numbers and "
                         "@/./+/-/_ characters."
        },
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
                'required': 'True',
            }
        ),
    )
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
                'required': 'True',
            }
        )
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password confirmation',
                'required': 'True',
            }
        ),
        help_text="Enter the same password as above, for verification."
    )

    class Meta:
        model = User
        fields = ("username", "password1", "password2",)

    def save(self, commit=True):
        _user = super(UserCreationForm, self).save(commit=False)
        _user.set_password(self.cleaned_data['password1'])
        if commit:
            _user.save()
        return _user


class LoginForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        # Set the label to omit ':'
        kwargs.setdefault('label_suffix', '')

        self.request = request
        self.user_cache = None
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
                'required': 'True',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
                'required': 'True',
            }
        )
    )


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(PostForm, self).__init__(*args, **kwargs)

    title = forms.CharField(
        required=True,
        max_length=300,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Title',
                }
            )
        )
    content = forms.CharField(
        widget=SummernoteWidget(
            attrs={
                'placeholder': 'Content',
            }
        )
    )
    tags = forms.CharField(
        label='Tag',
        required=False,
        max_length=200,
        help_text=u"Tags are separated by comma(,).",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    class Meta:
        model = Question
        fields = ('title', 'content', 'tags',)



class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(CommentForm, self).__init__(*args, **kwargs)

    content = forms.CharField(
        label='Comment',
        required=False,
        max_length=500,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Comment',
                'rows': '3',
            }
        )
    )

    class Meta:
        model = Comment
        fields = ('content',)

main/templates/main/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}자세히{% endblock %}
{% block head %}자세히 qna blog{% endblock %}
{% block subhead %}Post Your Any Question{% endblock %}
{% block img-bg %}{% static 'img/자세히-bg.jpg' %}{% endblock %}

<!-- Main Content -->
{% block content %}

    <h2 class="section-heading">Don't hesitate to have your question.</h2>
    <p>질문하는데 주저하지 마세요.</p>

    <blockquote>The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

{% endblock %}
<hr>

main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="qna blog">
    <meta name="author" content="studybee">

    <title>
        부흥고 동아리 | 2019
    </title>

    <!-- Clean Blog - Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Clean Blog - Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Clean Blog - Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


    <!-- Clean Blog - jQuery -->
    <!-- <script src="{% static 'js/jquery.js' %}"></script> -->

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript" charset="utf-8"></script>

    {% block external %}{% endblock %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">부흥고 동아리</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li>
                        <a href="#">Question</a> <!--{ % u r l ' p o s t ' % }-->
                    </li>
                    <li>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'logout_url' %}">{{ request.user.username }}, 로그아웃</a>
                        {% else %}
                            <a href="{% url 'login_url' %}">로그인</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% block img-bg %}{% endblock %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>
                            {% block head %}{% endblock %}
                        </h1>
                        <hr class="small">
                        <span class="subheading">
                            {% block subhead %}{% endblock %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                {% block content %}{% endblock %}

            </div>
        </div>
    </div>

    <hr>

    <!-- Footer - SNS -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            {# twitter #}
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            {# facebook #}
                            <a href="https://www.facebook.com/groups/studybee/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            {# github #}
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; studybee 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Clean-blog Core JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>
</html>

main/templates/main/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Contact</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="index.html">홈</a>
                    </li>
                    <li>
                        <a href="자세히.html">자세히</a>
                    </li>
                    <li>
                        <a href="post.html">Sample Post</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('img/contact-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->


                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>

main/templates/main/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}부흥고 동아리{% endblock %}
{% block head %}부흥고 동아리{% endblock %}
{% block subhead %}All 자세히 Question and Answer{% endblock %}
{% block img-bg %}{% static 'img/home-bg.jpg' %}{% endblock %}

{% block content %}

    {% for clublist in clublists %}
        <div class="post-preview">
            <a href="#">
                <h2 class="post-title">
                    <a href="chutzpah/">{{ clublist.ClubName }}</a>
                </h2>
                <form name="join" action="join" method="post">
                    {{ crsf_token }}
                    
                    <input type="hidden" name="username" value = "{{ username }}" />
                    <input type="hidden" name="clubname" value = "{{ clublist.ClubName }}" />

                    <input type="submit" name="submit" value="좋아요"/>
                </form>
            </a>
            <p class="post-meta">
                소개 : {{ clublist.ClubDescription }}<br>
                기장 : {{ clublist.ClubManager1 }} / 부기장 : {{ clublist.ClubManager2 }}<br>
                좋아요 : {{ clublist.ClubMemberSum }}
            </p>
        </div>
    {% empty %}
        There is yet article.
    {% endfor %}
    <br>

{% endblock %}

main/templates/main/post.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}post your question{% endblock %}
{% block head %}post ur question{% endblock %}
{% block subhead %}Feel Free to Ask Anything{% endblock %}
{% block img-bg %}{% static 'img/post-bg.jpg' %}{% endblock %}
{% block external %}

<!-- Tag-it - Theme CSS -->
<!--<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">-->
<link href="{% static 'css/tagit.ui-zendesk.css' %}" rel="stylesheet" type="text/css">

<!-- Tag-it - Essential CSS -->
<link href="{% static 'css/jquery.tagit.css' %}" rel="stylesheet" type="text/css">

<!-- Tag-it - JS -->
<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>-->

<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/tag-it.js' %}" type="text/javascript" charset="utf-8"></script>

<!-- Tag-it -->
<script type="text/javascript">
    $(document).ready(function() {
        var sampleTags = [];

        // ul tag
        $("#myTags").tagit();

        // input tag
        $('#id_tags').tagit({
            availableTags: sampleTags
        });
    });
</script>

{% endblock %}
<!-- Post Content -->
{% block content %}

<!-- post form -->
<form id="postform" class="form-horizontal" method="post" action="{% url 'post' %}">
    {% csrf_token %}

    <!-- Title input-->
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            {{ postform.title.label_tag }}
            {{ postform.title }}
            <span class="field-error">
            {{ postform.title.errors|striptags }}
            </span>
        </div>
    </div>

    <!-- Content input-->
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            {{ postform.content.label_tag }}
            {{ postform.content|safe }}
            <span class="field-error">
            {{ postform.content.errors|striptags }}
            </span>
        </div>
    </div>

    <!-- Tags input-->
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            {{ postform.tags.label_tag  }}
            {{ postform.tags }}
            {{ postform.tags.help_text }}
            <span class="field-error">
            {{ postform.tags.errors|striptags }}
            </span>
        </div>
    </div>

    <br>

    <!-- Post Button -->
    <div class="row">
        <div class="form-group col-xs-12">
            <button id="post" name="post" class="btn btn-block btn-default" type="submit">Post</button>
        </div>
    </div>

</form>
{% endblock %}
<hr>

main/templates/main/question.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{ question.title }}{% endblock %}

{% block head %}
    {% with question.title as title %}
        {{ title|truncatechars:20 }}
    {% endwith %}
{% endblock %}

{% block subhead %}
    Posted by {{ question.user.username }} on {{ question.updated_at }}
    <br>
    {% if question.tags.count %}
        <span class="glyphicon glyphicon-tag" aria-hidden="true" style="font-size: 0.7em;"></span>
        {% for tag in question.tags.all %}
            {% if forloop.last %}
                {{ tag }}
            {% else %}
                {{ tag }},
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock %}
{% block img-bg %}{% static 'img/question-bg.jpg' %}{% endblock %}
{% block content %}

<!-- title -->
<h1>
    {{ question.title }}
</h1>

<hr>
<!-- content -->
<p>
    {{ question.content|safe }}
</p>

<hr>
<!-- comment form -->
<p>
    <form id="commentform" class="form-horizontal" action="{{ request.path }}" method="post">
        {% csrf_token %}

        <!-- Comment content input-->
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
                {{ commentform.content.label_tag }}
                {{ commentform.content }}
                <span class="field-error">
                {{ commentform.content.errors|striptags }}
                </span>
            </div>
        </div>

        <!-- Comment Button -->
        <div class="row">
            <div class="form-group col-xs-12">
                <button id="comment" name="comment" class="btn btn-block btn-default" type="submit">Comment</button>
            </div>
        </div>

    </form>
</p>

<!-- view comments -->
<p>
    {% if question.comment_set.count %}
        {% for comment in question.comment_set.all %}
            <div class="row">
                <div class="col-xs-1">
                    <div>
                        <center><a href="{% url 'comment_popularity' comment_id=comment.id status='up' %}">
                            <span class="glyphicon glyphicon-menu-up" aria-hidden="true" style="font-size: 0.7em;"></span>
                        </a></center>
                    </div>
                    <div>
                        <center>
                            <span class="badge">
                                {{ comment.popularity }}
                            </span>
                        </center>
                    </div>
                    <div>
                        <center>
                            {% if comment.popularity != 0 %}
                                <a href="{% url 'comment_popularity' comment_id=comment.id status='down' %}">
                            {% endif %}

                            <span class="glyphicon glyphicon-menu-down" aria-hidden="true" style="font-size: 0.7em;"></span>

                            {% if comment.popularity != 0 %}
                                </a>
                            {% endif %}
                        </center>
                    </div>
                </div>
                <div class="col-xs-11">
                    <div>
                        {{ comment.content }}
                    </div>
                    <div><span style="font-size: 16px; font-style: italic;">
                        commented by {{ comment.user.username }} on {{ comment.created_at }}
                    </span></div>
                </div>
            </div>
            <hr>
        {% endfor %}
    {% else %}
        No found comments. Please be the first.
    {% endif %}
</p>

{% endblock %}